Algoritmo "Estrutura Para-Faça"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/04/2020
Var
// Seção de Declarações das variáveis 
   num, fatorial, contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o numero para calcular o fatorial: ")
   leia (num)
   fatorial := 1
   para contador de 1 ate num faca
        fatorial := fatorial * contador
   fimpara
   escreva ("O fatorial de ", num, " é: ", fatorial)
   
   
   
Fimalgoritmo