Algoritmo "Variaveis"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2020
Var
// Seção de Declarações das variáveis 
//   nota: inteiro, nota: real, nome: caractere, passou: logico
// primeiro nome
// segundo nome
// idade
// cidade
// endereço

   primeiroNome, segundoNome, cidade, endereco: caractere
   idade: inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo